Update what-is-an-activity.md
temporalio/documentation pull request #1143
Opened 2022-05-12 15:42 UTC by rachfop

## What does this PR do?
Hotjar Feedback Response #374
## Notes to reviewers
Cleaned up a few pieces around terms and added headers and a note.

2022-05-12 20:00 UTC, DJSanti commented on docs/concepts/what-is-an-activity.md
>  Therefore an Activity function is allowed to contain any code without restrictions.
Therefore, an Activity Definition has no restrictions on its contents. (and link to the page!)

2022-05-12 20:00 UTC, DJSanti commented on docs/concepts/what-is-an-activity.md
> +A Task Queue is essentially a queue used to store an Activity task until it is picked up by an available Worker.
I feel like this sentence can be merged with the one before it, and then you can discuss Workers.

2022-05-12 20:00 UTC, DJSanti commented on docs/concepts/what-is-an-activity.md
> +The Worker processes an Activity by invoking its implementation function.
So it runs an Activity Execution?

2022-05-12 20:00 UTC, DJSanti commented on docs/concepts/what-is-an-activity.md
> +Task Queues are queues that Workers listen on.
We explained this point about Activities, Workers, and Task Queues before this, so please remove.

2022-05-12 20:00 UTC, DJSanti commented on docs/concepts/what-is-an-activity.md
>  - An Activity can be implemented as a synchronous method or fully asynchronously involving multiple processes.
This sentence isn't necessary. The user coming here most likely knows about sync vs async

2022-05-12 20:00 UTC, DJSanti commented on docs/concepts/what-is-an-activity.md
>  - _Flow control_. A worker that consumes from a task queue asks for an Activity task only when it has available capacity. So workers are never overloaded by request spikes. If Activity executions are
Don't forget to capitalize Temporal terminology

2022-05-12 20:00 UTC, DJSanti commented on docs/concepts/what-is-an-activity.md
>  Temporal's SDK throttles this so a heartbeat may not be sent to the service until 80% of the heartbeat timeout has elapsed.
A Heartbeat may not be sent until 80% of the timeout has elapsed.

2022-05-16 17:15 UTC, flossypurse requested changes
It's awesome that you addressed the user feedback.

However, this whole page needs to be re-written from the ground up.

2022-05-23 22:53 UTC, closed without merging