Adds a note to Run ID topic
temporalio/documentation pull request #1509
Opened 2022-08-26 21:40 UTC by rachfop

## [Preview](https://deploy-preview-1509--mystifying-fermi-1bc096.netlify.app/workflows#run-id)
## What does this PR do?
[The discussion here](https://github.com/temporalio/api/pull/182) makes it clear that you shouldn't rely on a Run Id when deciding business logic. 

If a Workflow resets, it resets the Workflow History, which can lead to non-determinism issues if that ID is relied on.
## Notes to reviewers

This PR doesn't mention `original_execution_run_id` or `first_execution_run_id` as that goes above the need of the customer. Instructing one not to rely on the Run Id is much better than the logic needed to use the `original_execution_run_id`.

## Note

Used `caution` in the admonitions and not just `note` as this specific issue is notable.

## Note 2

The other random files were probably included from running prettier.

2022-08-26 21:57 UTC, djmagee commented on docs/concepts/what-is-a-run-id.md
> +Run Id is unsafe to be used in a Workflow Execution for any logical choices, as a reset operation might lead to non-determinism issues.
```suggestion
Run Id is unsafe to be used in a Workflow Execution for any logical choices because a reset operation can lead to non-determinism.
```

2022-08-29 15:47 UTC, flossypurse commented on docs/concepts/what-is-a-run-id.md
> +Run Id is unsafe to be used in a Workflow Execution for any logical choices because a reset operation can lead to non-determinism.
Unsafe for which logical choices?

Pretty sure it is safe for logical choices when it comes to visibility and listing and signal from a client - etc... 

Also, I can not find the discussion that mentions this - wrong link maybe?

2022-08-29 15:50 UTC, flossypurse requested changes

2022-08-29 15:50 UTC, flossypurse commented on docs/concepts/what-is-a-run-id.md
> +Run Id is unsafe to be used in a Workflow Execution for any logical choices because a reset operation can lead to non-determinism.
Unsafe for which logical choices?

Pretty sure it is safe for logical choices when it comes to visibility and listing and signal from a client - etc... 

Also, I can not find the discussion that mentions this - wrong link maybe?

2022-10-26 17:41 UTC, closed without merging