fix: PHP add workflow retries
temporalio/documentation pull request #1547
Opened 2022-09-06 13:06 UTC by seregazhuk

Resolves #1452

2022-09-06 13:36 UTC, flossypurse approved these changes

2022-09-06 13:36 UTC, flossypurse commented on docs/application-development/features.md
> +via `WorkflowOptions` for top-level Workflows:
```suggestion
A Retry Policy can be configured with an instance of the `RetryOptions` object.
To enable retries for a Workflow,  you need to provide a Retry Policy object via `ChildWorkflowOptions` for child Workflows or via `WorkflowOptions` for top-level Workflows.
```

2022-09-06 13:56 UTC, flossypurse requested changes
Just realized that this is being added to the app dev guide directly.

This content needs to be added as `/php/set-a-workflow-retry-policy` or something similar.

2022-09-07 15:15 UTC, seregazhuk commented
@flossypurse oops, fixed this one, and all my previous PR-s ✅

2022-09-07 19:10 UTC, flossypurse approved these changes

2022-09-07 19:12 UTC, flossypurse commented
awesome @seregazhuk ! lgtm!

2022-09-08 02:14 UTC, merged