TW-142 Adds KB on WF visibility
temporalio/documentation pull request #1771
Opened 2022-11-07 21:22 UTC by rachfop

## What does this PR do?

Adds a KB doc on different ways to check on WF visibility.

## Notes to reviewers

[Preview](https://temporal-documentation-cw5ar1il1.preview.thundergun.io/kb/visibility-status-of-running-workflow)

2022-11-15 04:51 UTC, djmagee commented on kb/visibility-status-of-running-workflow.md
> +Once you've integrated Elasticsearch with your Temporal Cluster, you can get information into the visibility of your running Workflows.
```suggestion
After you integrated Elasticsearch with your Temporal Cluster, you can get information into the visibility of your running Workflows.
```

2022-11-15 04:51 UTC, djmagee commented on kb/visibility-status-of-running-workflow.md
> +It isn’t recommended using the APIs with high-rate calls.
```suggestion
We don’t recommend using the APIs with high-rate calls.
```

2022-11-15 04:51 UTC, djmagee commented on kb/visibility-status-of-running-workflow.md
> +All APIs lists are paginated.
```suggestion
All lists from APIs are paginated.
```

2022-11-16 16:12 UTC, djmagee commented on kb/visibility-status-of-running-workflow.md
> +After you integrated Elasticsearch with your Temporal Cluster, you can get information into the visibility of your running Workflows.
```suggestion
After you integrate Elasticsearch with your Temporal Cluster, you can get information into the visibility of your running Workflows.
```
Oops. I missed this earlier. My bad.

2022-11-16 16:13 UTC, djmagee approved these changes
I missed one edit during my earlier pass.

2022-11-16 21:05 UTC, flossypurse requested changes
Just making sure this doesn't get merged too soon.
Per my last chat with @rachfop , we are looking at whether this should be massaged into concept explanations

2022-11-22 18:24 UTC, closed without merging