draft to see what else needs changing
temporalio/documentation pull request #1782
Opened 2022-11-10 20:03 UTC by DJSanti

## What does this PR do?

## Notes to reviewers

2022-11-10 21:06 UTC, feedmeapples commented on docs-src/tctl-v1/batch/describe.md
> +`tctl-v1` can run `batch` and `batch-v2` commands.
there is no need to mention `v1` in tctl v1 docs because v1 is the only official version of tctl. There is not going to be v2

2022-11-10 21:07 UTC, feedmeapples commented on docs-src/tctl-next/batch/index.md
> +- [tctl batch describe --job_id](/tctl-next/batch-v2#describe)
in tctl next the flag is

tctl next also doesn't have `batch-v2` command, only `batch`

```suggestion
- [tctl batch describe --job-id](/tctl-next/batch#describe)
```

2022-11-10 21:07 UTC, feedmeapples commented on docs-src/tctl-v1/workflow/describeid.md
> +tctl workflow describeid <workflow_id> --print_raw <id>
why is this changed?

2022-11-10 21:09 UTC, feedmeapples requested changes

2022-11-10 21:09 UTC, feedmeapples commented on docs-src/tctl-v1/workflow/signal.md
> +tctl workflow signal --query --name <name>
```suggestion
tctl workflow signal --query <query> --name <name>
```

2022-11-10 21:09 UTC, feedmeapples commented on docs-src/tctl-v1/workflow/signal.md
> +tctl workflow signal --query --name <name>
same for other places

2022-11-10 21:09 UTC, feedmeapples commented on docs-src/tctl-v1/workflow/terminate.md
> +tctl workflow terminate  --run_id <id>
```suggestion
tctl workflow terminate --run_id <id>
```

2022-11-10 21:10 UTC, feedmeapples commented
approving with an assumption that the remaining comments are addressed

2022-11-10 21:11 UTC, feedmeapples approved these changes

2022-11-10 21:14 UTC, DJSanti commented on docs-src/tctl-v1/workflow/describeid.md
> +tctl workflow describeid <workflow_id> --print_raw <id>
because the example is for --print-raw

2022-11-14 19:09 UTC, aarohib commented on docs-src/tctl-v1/workflow/signal.md
> +Workflows can also listen for Queries.
Is this a [Query](https://docs.temporal.io/workflows#query) or just a --query (a SQL query) that can be passed with the Signal?

2022-11-14 19:12 UTC, aarohib commented on docs-src/tctl-v1/workflow/signal.md
> +tctl workflow signal --workflow_id <id> [modifiers]
should this be `<modifiers>`?

2022-11-14 19:12 UTC, aarohib commented on docs-src/tctl-v1/workflow/signal.md
> +tctl workflow signal --query <query> [modifiers]
should this be `<modifiers>`?

2022-11-17 19:50 UTC, flossypurse approved these changes

2022-11-18 16:12 UTC, merged