Add shortlinks to API references
temporalio/documentation pull request #1863
Opened 2023-01-03 02:46 UTC by lorensr

## What does this PR do?

## Notes to reviewers

2023-01-03 21:03 UTC, flossypurse commented
Hmm... not sure how I feel about this tbh.
<img width="705" alt="Screen Shot 2023-01-03 at 2 03 32 PM" src="https://user-images.githubusercontent.com/34380806/210441048-3a6965e7-2958-4504-811c-b7c151f60424.png">

2023-01-03 21:37 UTC, lorensr commented
I think they're helpful to know / people appreciate knowing them, and this seemed a place most likely to be seen. A possible alternative for all but Java is displaying the short link at the index of the API reference sites

2023-01-24 18:26 UTC, flossypurse requested changes
The general consensus is that this clutters the UX.
How about we put these in each of the lang api-reference nodes like this one: https://github.com/temporalio/documentation/blob/main/docs-src/go/api-reference-go.md

And then those will publish to the dev guide here: https://temporal-documentation-93but6zbt.preview.thundergun.io/application-development/foundations#api-reference

2023-02-17 15:11 UTC, flossypurse approved these changes

2023-02-17 21:04 UTC, merged