TW 246: update limit sheet
temporalio/documentation pull request #1898
Opened 2023-01-19 22:12 UTC by DJSanti

This PR addresses a recent Slack thread that made a note of limits applying to parallel Events across Cloud, rather than per Workflow. I added a sentence at the start that should make it clear that all Event limits on this page apply to Events running in parallel. Could use feedback, so please let me know what else should change.

2023-01-20 20:25 UTC, djmagee requested changes

2023-01-20 20:25 UTC, djmagee commented on kb/temporal-platform-limits-sheet.md
> +Unless otherwise stated, Event limits apply to all Events running in parallel on a system.
For Events, "occurring" seems to be a better verb than "running". I'm also unsure what "in parallel" means in this context. I doubt that "simultaneously" is accurate, but I don't know what bounding period might be appropriate.

2023-01-23 15:49 UTC, djmagee approved these changes

2023-01-23 16:02 UTC, merged

2023-01-24 21:01 UTC, DJSanti commented
Remaking this ticket. Did not go through proper channels for approval. Oversight.