Add Schedule a Workflow in TypeScript and Python
temporalio/documentation pull request #1943
Opened 2023-02-22 21:36 UTC by rachfop

## What does this PR do?
Adds samples for Python and TypeScript. 

TW-283
TW-356

## Notes to reviewers

https://github.com/temporalio/features/issues/153
PHP and Java aren't currently supported.

2023-02-23 01:36 UTC, bergundy commented on docs-src/python/how-to-set-a-schedule-in-python.md
> +Use the [create_schedule()](https://python.temporal.io/temporalio.client.Client.html#create_schedule) method available in the [Client](https://python.temporal.io/temporalio.client.Client.html) class
```suggestion
Use the [create_schedule()](https://python.temporal.io/temporalio.client.Client.html#create_schedule) method available in the [Client](https://python.temporal.io/temporalio.client.Client.html) class to create a new Schedule for a Workflow Execution.
```

2023-02-23 01:38 UTC, bergundy commented on docs-src/python/how-to-set-a-schedule-in-python.md
> +Define the parameters of the Schedule, then call the `create_schedule()` method on the Client object and pass in the Workflow Id for the Workflow you want to schedule, as well as the Schedule object
Where's the action in this sample?
And note that both the workflow and schedule have IDs.

2023-02-23 01:42 UTC, bergundy commented on docs-src/python/how-to-set-a-schedule-in-python.md
> +                )
Please split this into multiple samples, one for cron, one for running on a specific interval and one using the calendar.
I'd also add comments about these fields and mention what defaults they have.

2023-02-23 01:42 UTC, bergundy commented on docs-src/python/how-to-set-a-schedule-in-python.md
> +                )
This part specifically requires an explanation.

2023-02-23 01:43 UTC, bergundy commented on docs-src/typescript/how-to-set-a-schedule-in-typescript.md
> +      // ],
This is clearer than the Python sample IMHO.

2023-02-23 01:43 UTC, bergundy commented on docs/application-development/features.md
> +The information you are looking for may be found in the [legacy docs](https://legacy-documentation-sdks.temporal.io/).
Can we not direct users to the legacy docs?

2023-02-23 01:43 UTC, bergundy commented on docs-src/typescript/how-to-set-a-schedule-in-typescript.md
> +    },
Requires some explanation.

2023-02-23 01:44 UTC, bergundy reviewed
Is there going to be a follow up PR(s) showing how to update, list, describe, and delete schedules?

2023-02-28 15:18 UTC, flossypurse requested changes
I would like us to focus on using snipped examples from the samples repo.

2023-05-15 17:11 UTC, closed without merging