EDU-938: corrected Query link in CLI docs
temporalio/documentation pull request #2227
Opened 2023-07-25 16:19 UTC by DJSanti

## What does this PR do?
This PR corrects a link in the CLI documentation.

2023-07-25 17:01 UTC, flossypurse requested changes

2023-07-26 00:00 UTC, djmagee commented on docs-src/cli/cmd-options/query.md
> +See the [temporal workflow list](/cli/workflow/list).
```suggestion
For details, see the [temporal workflow list](/cli/workflow/list) command.
```

2023-07-26 17:36 UTC, djmagee commented
Needs a new build but otherwise looks good.

2023-07-26 20:59 UTC, djmagee approved these changes

2023-07-26 21:09 UTC, flossypurse approved these changes

2023-07-26 21:11 UTC, merged