EDU-965: tag CLI source nodes
temporalio/documentation pull request #2245
Opened 2023-07-28 18:29 UTC by DJSanti

## What does this PR do?
This PR adds additional tags to CLI source nodes.

## Notes to reviewers
Branch had better be cleared up.

2023-08-01 21:15 UTC, flossypurse requested changes

2023-08-01 21:15 UTC, flossypurse commented on docs-src/cli/activity/index.md
> +<<<<<<< HEAD
merge issue

2023-08-02 12:03 UTC, flossypurse requested changes
Just revert the `cli-reference` change.

The tag needs to be `cli reference` - no space.

Otherwise, looking good.

2023-08-02 12:03 UTC, flossypurse commented on docs-src/cloud/tcld/account/get.md
> +  - cli-reference
make sure these are `cli reference` - no space

2023-08-02 15:22 UTC, DJSanti commented
@flossypurse Got the hyphens out. Just need your OK on this.

2023-08-02 16:39 UTC, merged