Add bit about going unversioned->versioned
temporalio/documentation pull request #2253
Opened 2023-07-31 22:43 UTC by Sushisource

Wanted to add a bit about how you can go from unversioned to versioned queues/workers.

2023-08-02 19:12 UTC, DJSanti requested changes
Made some changes for easier flow.

2023-08-02 19:12 UTC, DJSanti commented on docs-src/concepts/what-is-worker-versioning.md
> +be processed by unversioned Workers, and any new Workflows will be processed by Workers with the new Build ID.
```suggestion
To migrate from an unversioned Task Queue, add a new default Build ID to the Task Queue.
From there, deploy Workers with the same Build ID.
Open Workflows will continue to be processed by unversioned Workers; new Workflow Executions will be process by Workers with the new Build ID.
```

2023-08-02 19:13 UTC, DJSanti commented
@Sushisource Whenever you can, please make changes and update this branch.

2023-08-08 18:20 UTC, flossypurse approved these changes

2023-08-08 18:20 UTC, flossypurse commented on docs-src/concepts/what-is-worker-versioning.md
> +Open Workflows will continue to be processed by unversioned Workers; new Workflow Executions will be process by Workers with the new Build ID.
```suggestion
Unversioned Workers will continue processing open Workflows, while Workers with the new Build ID will process new Workflow Executions.
```

2023-09-28 17:15 UTC, rachfop approved these changes

2023-09-28 17:19 UTC, merged