EDU-989: add update item to Go feature TOC
temporalio/documentation pull request #2260
Opened 2023-08-02 18:50 UTC by DJSanti

## What does this PR do?
This PR provides a link to the Updates section of the Go Dev Guide

## Notes to reviewers

2023-08-07 18:45 UTC, flossypurse requested changes

2023-08-07 18:45 UTC, flossypurse commented on docs-src/go/features.md
> +- [How to develop updates](#updates)
This is a source node - so you can use the id of the node, and link magic rewrites -

2023-08-07 18:45 UTC, flossypurse commented on package.json
> +    "latest": "^0.2.0",
what is this?

2023-08-07 20:25 UTC, DJSanti commented on package.json
> +    "latest": "^0.2.0",
not sure

2023-08-16 16:21 UTC, flossypurse requested changes
The are 2 places where the link needs to be added.

2023-08-16 23:21 UTC, djmagee commented on docs-src/go/features.md
> +- [How to develop updates](/go/updates)
```suggestion
- [How to develop with Updates](/go/updates)
```

2023-08-17 19:49 UTC, flossypurse requested changes

2023-08-17 19:49 UTC, flossypurse commented on yarn.lock
> -  resolved "https://registry.yarnpkg.com/combined-stream/-/combined-stream-1.0.8.tgz#c3d45a8b34fd730631a110a8a2520682b31d5a7f"
We use yarn.
So, I don't know why this is changing to npmjs ?

Need to back this out.

2023-08-18 19:26 UTC, merged