EDU-1023: tag Go testing nodes
temporalio/documentation pull request #2275
Opened 2023-08-09 16:56 UTC by DJSanti

## What does this PR do?
This PR adds tags to the source nodes for the Testing section of the Go SDK.

2023-08-09 17:26 UTC, flossypurse requested changes

2023-08-09 17:26 UTC, flossypurse commented on docs-src/go/listen-to-heartbeats.md
> +  - testing-guide-doc-type
i like `how-to doc type` and `explanation doc-type` and `reference doc-type`

Not sure about these others at this point.

2023-08-09 17:26 UTC, flossypurse commented on docs-src/go/mock-activities.md
> +  - activities
```suggestion
  - activity
```
I think we decided to use singular in these cases.

2023-08-09 17:26 UTC, flossypurse commented on docs-src/go/skip-time-set-up.md
> +  - workflows
singular

2023-08-16 16:33 UTC, flossypurse requested changes
Just curious what is the difference in your opinion between these tags?
  - testing
  - testing-guide-doc-type

2023-08-18 14:49 UTC, napcs approved these changes

2023-08-18 14:50 UTC, merged