Fix activity interfaces
temporalio/documentation pull request #2299
Opened 2023-08-19 08:44 UTC by roxblnfk

## What does this PR do?

Fixes documentation typos

## Notes to reviewers

2023-08-19 09:13 UTC, butschster requested changes

2023-08-19 09:13 UTC, butschster commented on docs/dev-guide/phplang/foundations.md
>  #[YourWorkflowInterface]
```suggestion
#[WorkflowInterface]
```

2023-10-10 17:13 UTC, napcs commented
@roxblnfk Thanks for the PR. I'm sorry for the late response.

It looks like you've made modifications to the generated file in the `docs` directory, rather than the source files. See the README.md file in the repository for contribution and build instructions. 

The short version is you should make changes to the appropriate files in the `docs-src` directory, and then run the local build steps to ensure things get built correctly. 

Let me know if I can help.

2023-10-11 08:48 UTC, roxblnfk commented
Hi @napcs.
I followed [this guide](https://github.com/temporalio/documentation#how-to-fix-a-typo) and I got this error when trying to build the docs:
![image](https://github.com/temporalio/documentation/assets/4152481/69d72eca-9147-4402-8791-ac7047414819)
It would be nice if we could buld docs using a tested docker image.

2023-10-11 09:09 UTC, roxblnfk commented
Reopened in #2379

2023-10-11 09:09 UTC, closed without merging