EDU-1026: add Cloud latency info
temporalio/documentation pull request #2309
Opened 2023-08-25 17:38 UTC by DJSanti

## What does this PR do?
This PR adds additional information to the end of `operating-envelope-latency` concerning latency.

2023-08-25 19:03 UTC, lorensr approved these changes

2023-08-25 19:03 UTC, lorensr commented on docs-src/cloud/operating-envelope-latency.md
> +Be aware that the latency observed on the Temporal Client might be impacted by other system components, such as the Codec Server, egress proxy, and the network itself.
```suggestion
The latency observed from the Temporal Client might be impacted by other system components, such as the Codec Server, egress proxy, and the network itself.
```

I like avoiding commands, and to some extent every sentence in the docs is "be aware". If important enough, would add a warning block, but don't think important enough here

2023-08-25 19:04 UTC, djmagee commented on docs-src/cloud/operating-envelope-latency.md
> +Be aware that the latency observed on the Temporal Client might be impacted by other system components, such as the Codec Server, egress proxy, and the network itself.
```suggestion
Be aware that the latency observed on the Temporal Client might be affected by other system components, such as the Codec Server, egress proxy, and the network itself.
```
Per https://developers.google.com/style/word-list#impact.

2023-08-28 14:16 UTC, flossypurse requested changes

2023-08-28 14:16 UTC, flossypurse commented on docs-src/cloud/operating-envelope-latency.md
> +The latency observed from the Temporal Client might be affected by other system components, such as the Codec Server, egress proxy, and the network itself.
```suggestion
Other system components, such as the Codec Server, egress proxy, and the network itself, could impact the latency observed from the Temporal Client.
```

passive -> active

2023-08-28 16:50 UTC, merged