Adds link checker
temporalio/documentation pull request #2394
Opened 2023-10-13 16:53 UTC by rachfop

## What does this PR do?

**Run**: `yarn link-checker`

**Before**
```
hyperlink build/ --sources docs-src/                
Reading files
Checking 26125 links from 1142 files (479 documents)
Found some broken links, reading source files
docs-src/cloud/what-is-audit-logging.md
  error: bad link /cloud/index at line 13

docs-src/concepts/what-is-the-temporal-web-ui.md
  error: bad link /cli/index at line 12

docs-src/references/cluster-metrics.md
  error: bad link /cloud/index at line 14

docs-src/references/sdk-metrics.md
  error: bad link /cloud/index at line 14

docs-src/typescript/troubleshoot-issues.md
  error: bad link /dev-guide/typescript/dev-guide/typescript/foundations at line 64
```
**After**

```
hyperlink build/ --sources docs-src/
Reading files
Checking 26125 links from 1142 files (479 documents)
Found 0 bad links
```
## Notes to reviewers

2023-10-13 17:10 UTC, axfelix commented
Nice work adding this! Should we put a note in the readme about the workflow too? Otherwise, looks great.

2023-10-13 17:10 UTC, axfelix approved these changes

2023-10-17 18:19 UTC, flossypurse requested changes
Let's do this in 2 phases - 
First - lets add the tool and any documentation to the README so folks now how to use it and when to use it - etc..

Then, let's do another separate change where we fix the broken links.

2023-10-17 20:25 UTC, rachfop commented
https://github.com/temporalio/documentation/pull/2403
@flossypurse

2023-10-17 20:25 UTC, closed without merging