migrate kb articles to cluster deployment and production readiness
temporalio/documentation pull request #2428
Opened 2023-10-23 19:06 UTC by axfelix

3 more KB migrations:

https://temporalio.atlassian.net/browse/EDU-1275

https://temporalio.atlassian.net/browse/EDU-1283

https://temporalio.atlassian.net/browse/EDU-1280

2023-10-23 22:15 UTC, djmagee commented on docs-src/prod-readiness-context/platform-defaults.md
> +title: Temporal Platform Defaults
```suggestion
title: Temporal Platform defaults
```

2023-10-23 22:15 UTC, djmagee commented on docs-src/prod-readiness-context/platform-defaults.md
> +For the latest information on the Temporal Cloud limits, see [Temporal Cloud limits sheet](/cloud/operating-envelope#default-limits).
```suggestion
For the latest information on the Temporal Cloud default limits, see [What are the Temporal Cloud default limits?](/cloud/operating-envelope#default-limits)
```

2023-10-23 22:15 UTC, djmagee commented on docs-src/concepts/what-is-an-update.md
> +   See the [Temporal Platform limits](/production-readiness/tuning#platform-defaults) for more details.
```suggestion
   For more details, see the [Temporal Platform defaults](/production-readiness/tuning#platform-defaults).
```

2023-10-24 01:01 UTC, axfelix commented on docs-src/cloud/prometheus-grafana-setup-cloud.md
> +See the example Grafana configuration described in the [Prometheus and Grafana setup for open-source Temporal Cluster](/production-readiness/monitoring#prometheus-grafana-setup) article.
Yeah, good call! I like the more specificity!

2023-10-24 01:07 UTC, axfelix commented on docs-src/cluster-ops-context/intro.md
> +### Docker & Docker Compose
I'll have to update the anchor in several places if we make this change... not sure if our style guide is anti-ampersand but putting a pin in it for now!

2023-10-24 16:22 UTC, rachfop approved these changes

2023-10-24 16:24 UTC, flossypurse requested changes
blocking to prevent accidental merge.

2023-10-24 22:46 UTC, axfelix commented
Now also handles https://temporalio.atlassian.net/browse/EDU-1278 and https://temporalio.atlassian.net/browse/EDU-1279

2023-10-31 18:32 UTC, axfelix commented
ES6 migration page is now at https://community.temporal.io/t/migrating-visibility-data-from-elasticsearch-6/9970, as discussed, which addresses https://temporalio.atlassian.net/browse/EDU-1336.

2023-11-07 16:44 UTC, flossypurse commented
Moved off of a forked branch onto this: https://github.com/temporalio/documentation/pull/2463

2023-11-22 15:38 UTC, flossypurse commented
commits merged in this PR: https://github.com/temporalio/documentation/pull/2463

2023-11-22 15:38 UTC, closed without merging