Temporal Cloud now support KeywordList
temporalio/documentation pull request #2687
Opened 2024-03-15 01:09 UTC by rachfop

## What does this PR do?

Supports up to 40.

## Notes to reviewers

2024-03-15 16:36 UTC, flossypurse approved these changes

2024-03-18 17:06 UTC, rodrigozhou requested changes

2024-03-18 17:06 UTC, rodrigozhou commented on docs-src/cloud/limits.md
> +| KeywordList           | 40    |
```suggestion
| Keyword               | 40    |
| KeywordList           | 5     |
```

2024-03-18 17:07 UTC, rodrigozhou approved these changes

2024-03-18 17:07 UTC, antmendoza approved these changes

2024-03-18 17:08 UTC, merged