Improves SEO for all docs
temporalio/documentation pull request #2840
Opened 2024-05-16 05:00 UTC by rachfop

Adds SEO related description for docs.

[View the diff without whitespace changes](https://github.com/temporalio/documentation/pull/2840/files?w=1)

2024-05-17 15:48 UTC, napcs requested changes

2024-05-17 15:48 UTC, napcs commented on docs/cli/index.mdx
> +description: "Manage and debug Temporal Applications with the Temporal CLI, a powerful tool for starting, stopping, and inspecting workflows and activities. With features like namespace management, d
Recommend keeping between 50 and 160 characters, and very focused. Google truncates at 160 chars.

2024-05-20 13:20 UTC, flossypurse commented on docs/encyclopedia/activities.mdx
> +description: Activities are the building blocks of Temporal workflows. Learn about the different types of activities, including how to define and execute activities, how to handle activity timeouts,
```suggestion
description: Activities are the building blocks of Temporal Workflows. Learn about the different types of Activities, including how to define and execute Activities, how to handle activity timeouts, and how to handle activity retries.
```

Double check for core term capitalization.

2024-06-04 14:51 UTC, flossypurse commented
Implemented with https://github.com/temporalio/documentation/pull/2882

2024-06-04 14:51 UTC, closed without merging