Moving introduction to temporal cloud under evaluate
temporalio/documentation pull request #2971
Opened 2024-07-23 14:22 UTC by jsundai

## What does this PR do?
- moves intro to temporal cloud (overview, pricing, etc) to evaluate after features
- adds overview page into the sidebar 

## Notes to reviewers

2024-07-29 17:18 UTC, MasonEgger requested changes

2024-07-29 17:18 UTC, MasonEgger commented on docs/evaluate/temporal-cloud/overview.mdx
> +[Temporal Cloud](https://temporal.io/cloud) serves as a software-as-a-service (SaaS) infrastructure platform, specifically designed to manage the durability of your Temporal Applications.
Do we hyphenate this?  There's a lot of different ways, and I'll admit I don't know ours. If we do, just decline this suggestion. 

```suggestion
[Temporal Cloud](https://temporal.io/cloud) serves as a software as a service (SaaS) infrastructure platform, specifically designed to manage the durability of your Temporal Applications.
```

2024-07-29 17:18 UTC, MasonEgger commented on docs/evaluate/temporal-cloud/overview.mdx
> +- [RBAC](/cloud/saml): Temporal Cloud provides RBAC which supports SAML Single Sign-On (SSO) authentication. This provides a secure and seamless way for users to access Temporal Cloud resources using
We shouldn't assume users will know that acronym. 

```suggestion
- [Role Based Access Control (RBAC)](/cloud/saml): Temporal Cloud provides RBAC which supports SAML Single Sign-On (SSO) authentication. This provides a secure and seamless way for users to access Temporal Cloud resources using their organization's credentials, simplifying user management and enhancing security.
```

2024-07-29 17:18 UTC, MasonEgger commented on docs/evaluate/temporal-cloud/overview.mdx
> +There are two major parts of the Temporal Platform that work together to create the fully functioning system.
This sections seems to be generically describing Temporal, yet it lists Temporal Cloud as the second part. Should this be Temporal Service, in which we state that Temporal Cloud is an offering of the Temporal Service.

2024-08-09 15:46 UTC, axfelix approved these changes
Approving pending Mason's comments

2024-08-13 14:48 UTC, merged