Java SDK message passing docs
temporalio/documentation pull request #3008
Opened 2024-08-13 15:57 UTC by Quinn-With-Two-Ns

## What does this PR do?
 * Copied message-passing section from https://github.com/temporalio/documentation/pull/2976 (as of when this branch was created) and altered for Java
 * Replaced most uses of `async` in docs with blocking, kept headers for cross language consistency but open to change
 * Left `Exceptions ` section blank for now till Pythons is done
 ## Notes to reviewers

2024-08-13 20:43 UTC, fairlydurable commented
This appears to be https://temporalio.atlassian.net/browse/SDK-1752
Which will eventually become https://temporalio.atlassian.net/browse/EDU-670

Please let me know if I've mis-identified the PR draft.

2024-08-14 18:32 UTC, dandavison approved these changes
Awesome, thanks very much @Quinn-With-Two-Ns. I pushed two commits to brind up to date with the Python docs.

Over to you @fairlydurable!

2024-09-13 17:26 UTC, angelazhou32 commented on docs/develop/python/message-passing.mdx
> +You specify the condition by passing a function that returns `True` or `False`.
Do you want to mention the timeout?

2024-09-13 18:22 UTC, dandavison commented on docs/develop/python/message-passing.mdx
> +You specify the condition by passing a function that returns `True` or `False`.
Good call! Done.

2024-09-13 18:37 UTC, fairlydurable approved these changes
@angelazhou32 Performed team review.
@dandavison responded to Angela's review.

I performed a light sanity check after this process.

Stamping.

2024-09-16 18:21 UTC, fairlydurable requested changes
Light passes on all of these due to time limits

* Spellcheck, grammar check
* Caps check
* Overall inspection

2024-09-16 18:21 UTC, fairlydurable commented on docs/develop/java/message-passing.mdx
> +- A Query handler must not modify workflow state.
```suggestion
- A Query handler must not modify Workflow state.
```

2024-09-16 18:21 UTC, fairlydurable commented on docs/develop/java/message-passing.mdx
> +  - Define an update validator with the `@UpdateValidatorMethod` annotation.
```suggestion
  - Define an Update validator with the `@UpdateValidatorMethod` annotation.
```

2024-09-16 18:21 UTC, fairlydurable commented on docs/develop/java/message-passing.mdx
> +A client sending an Update must wait until the Server delivers the Update to a Worker.
```suggestion
A Client sending an Update must wait until the Server delivers the Update to a Worker.
```

2024-09-16 18:21 UTC, fairlydurable commented on docs/develop/java/message-passing.mdx
> +- **The workflow does not exist**:
```suggestion
- **The Workflow does not exist**:
```

2024-09-16 19:28 UTC, fairlydurable approved these changes

2024-09-16 19:33 UTC, merged