Adding in rps and aps in the glossary
temporalio/documentation pull request #3010
Opened 2024-08-13 21:28 UTC by jsundai

## What does this PR do?
Adds actions per second and requests per second into the glossary. 

## Notes to reviewers
See: JIRA [EDU-2731](https://temporalio.atlassian.net/browse/EDU-2731)

2024-08-13 22:47 UTC, axfelix approved these changes

2024-08-14 14:26 UTC, fairlydurable commented on docs/glossary.md
> +RPS, or Requests Per Second, is used in the Temporal Service (both in self-hosted Temporal and Temporal Cloud). This is a measure that controls the rate of requests at the service level, such as the
Requests per second (RPS) measures the rate at which Service-level requests such as Frontend, History, or Matching Service requests are processed.
Namespaces use RPS rate limits to ensure that Workflow Executions run smoothly, even during request spikes.

2024-08-14 14:28 UTC, fairlydurable requested changes
Please look at wording suggestions, and note that A in APS is Actions, capitalized, and per second, is not. RPS is all lowercased when put into words.

This applies to the header level (we use sentence casing) as well as the definitions.

2024-08-14 14:50 UTC, jsundai commented on docs/glossary.md
> +APS, or Actions Per Second, is specific to Temporal Cloud.
This is mostly about the definition of Actions. I'm thinking we could add this information to that definition.

2024-08-15 20:29 UTC, merged