tcld nexus docs
temporalio/documentation pull request #3151
Opened 2024-10-12 03:16 UTC by prasek

## What does this PR do?

Adds `tcld nexus` docs

## Notes to reviewers

Auto generated from https://github.com/prasek/tcld/tree/nexus-tcld-docs

2024-10-14 14:30 UTC, fairlydurable requested changes
One typo

2024-10-14 14:30 UTC, fairlydurable commented on docs/production-deployment/cloud/tcld/nexus.mdx
> +These commmands manage the allowed namespaces for a Nexus Endpoint.
```suggestion
These commands manage the allowed namespaces for a Nexus Endpoint.
```

2024-10-14 17:29 UTC, prasek commented
thanks @fairlydurable, addressed comments and should be good to go!

2024-10-23 14:04 UTC, fairlydurable approved these changes
All files read. This material aligns with existing CLI doc form.

I don't want to get in the way of the ticket. If this needs to be out there, there are no issues that would prevent this going live. I am approving this ticket.

I would strongly recommend a second pass on a follow-up ticket:

- The tags are not in alignment with our new SEO optimization (cc @napcs)
- The layout of the page can be substantially improved for readability. We can sync and I'd be happy to mock up suggestions.
- If this material is auto-generated and should not be directly edited (and instead go through the tcld team), that should be noted loudly in the file, whether with comments, metadata, or other non-user-facing element.

Also cc'ing in @josh-berry and @yuandrew since this feedback will likely affect Temporal CLI doc generation.

2024-10-23 15:39 UTC, merged