Update java-helloworld.md
temporalio/documentation pull request #349
Opened 2021-04-13 09:47 UTC by mnabe

If you select/add Gradle through IntelliJ when creating a new project, I am not sure that `App.java` is neccessarily generated, like it is when you initialize gradle through command-line with `gradle init`. Therefore, I changed the sentence a bit to clarify for people who initialize project/gradle in the former way, that they may not see that specific file.

## What was changed:

## Why?

## Checklist

1. Closes issue: 

2. How was this tested:

3. Any docs updates needed?

2021-04-13 09:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/temporalio/documentation?pullRequest=349) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/temporalio/documentation?pullRequest=349) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/temporalio/documentation?pullRequest=349) it.</sub>

2021-04-13 18:20 UTC, flossypurse commented
Thank you @mnabe ! We really appreciate this contribution to make things more clear.

Post a comment when you feel your changes are ready for review.

2021-04-19 08:00 UTC, mnabe commented
@flossypurse Sorry for the small delay. The changes are now ready to be reviewed. Thanks for welcoming me/the changes, even though it is only a few sentences! You can take a look, hope you can use it.

2021-04-19 14:11 UTC, flossypurse requested changes
Overall, these are really great changes to make the experience better. We really, really appreciate this. 

If you don't mind addressing the 2 pieces of feedback, then we will definitely get this merged.

2021-04-19 18:02 UTC, mnabe commented
Thanks a lot for the feedback, I agree with your suggestions! I think I have committed all your suggestions to changes, otherwise let me know if I missed something and further action is required

2021-04-19 18:07 UTC, flossypurse approved these changes

2021-04-19 18:08 UTC, merged