[WIP] Docs Redesign
temporalio/documentation pull request #633
Opened 2021-09-13 12:35 UTC by m-abdelwahab

## What does this PR do?

This PR is a revamp for the entire docs website.  Homepage, docs page, and blog. 

| Before                                                                                                                            | After                                                                                                                             |
|-----------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------|
| <img src="https://user-images.githubusercontent.com/27310414/133084150-b692eba0-3385-43ad-830d-32264cdb7d22.png" width="1024px"/> | <img src="https://user-images.githubusercontent.com/27310414/133083782-b2977c4c-f9df-4301-ba85-e5b45c2a50b7.png" width="1024px"/> |

2021-09-15 16:08 UTC, sw-yx commented on src/components/SDKs.js
> +        <Link to={useBaseUrl("/docs/concepts/introduction")}>
```suggestion
        <Link to={useBaseUrl("/docs/node/introduction")}>
```

2021-10-10 07:02 UTC, sw-yx approved these changes
looks like /application-development was deleted, be sure to add in a redirect

2021-10-10 07:03 UTC, sw-yx requested changes
netlify looks like it is failing on the glossary page also disappearing.

```
12:00:53 AM:   ✖ FAIL load build/docs/glossary
12:00:53 AM:   | operator: load
12:00:53 AM:   | expected: 200 build/docs/glossary
12:00:53 AM:   |   actual: ENOENT: no such file or directory, open '/opt/build/repo/build/docs/glossary'
12:00:53 AM:   |       at: build/404.html:20:4905 <a class="footer__link-item" href="/docs/glossary">...</a>
12:00:53 AM:   ✖ FAIL load build/blog/tags/bugs
12:00:53 AM:   | operator: load
12:00:53 AM:   | expected: 200 build/blog/tags/bugs
12:00:53 AM:   |   actual: ENOENT: no such file or directory, open '/opt/build/repo/build/blog/tags/bugs'
12:00:53 AM:   |       at: build/blog/index.html:20:21716 <a class="mr-2 my-2 no-underline inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium bg-[color:var(--ifm-badge-background-color)] text-[color:var(--ifm-color)] hover:opacity-80" href="/blog/tags/bugs">...</a>
```

2021-10-29 23:24 UTC, sw-yx commented on src/components/Intro.js
> +        <h3 className="text-xl font-semibold mb-4">System Tools</h3>
Yes. and "Dev Tools", not "Developer Tools" - its cleaner

2021-10-30 01:09 UTC, flossypurse approved these changes

2021-10-30 01:12 UTC, merged